services:
  strapi1:
    image: 513160854534.dkr.ecr.eu-west-2.amazonaws.com/list-learner/dev-registry:latest
    container_name: listlearner_dev_strapi1
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1338:1337"
    restart: always
  strapi2:
    image: 513160854534.dkr.ecr.eu-west-2.amazonaws.com/list-learner/dev-registry:latest
    environment:
      container_name: listlearner_dev_strapi2
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1339:1337"
    restart: always
  haproxy:
    container_name: listlearner_dev_haproxy
    image: haproxy:latest
    depends_on:
      - strapi1
      - strapi2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "${HAPROXY_PORT}:80"
    environment:
      - HAPROXY_PORT=${HAPROXY_PORT:-80}
